### ISSUE TITLE
[BUG] https://disease.sh/v3/covid-19/continents/oceania doesn't work

### ISSUE THREAD

**Issue by nnguyen52** [disease-sh/API#1003]
Can you fix this endpoint (https://disease.sh/v3/covid-19/continents/oceania ) 

Thank you!  <3

**Comment by puf17640** [comment]
I'm currently looking into it but please bear with me, I'm hungover and my laptop has 4% battery left.

**Comment by puf17640** [comment]
hm, seems we never wrote tests to check if all continent endpoints are actually working... I'll post the issue in the discord server, maybe someone has time to fix this properly!

**Comment by neo7337** [comment]
For this issue, it is found that here strict checking is not working properly
https://github.com/disease-sh/API/blob/master/utils/nameUtils.js#L87

in case of strict `checking==true` we should be doing fuzzySearch() otherwise we can go with the logic present here : `stringUtils.wordsStandardize(ctry[selector]) === standardizedName`

lemme know if this feels right?

in case of australia/oceania strict checking should be always true otherwise it won't get the data

**Comment by neo7337** [comment]
if `strict` flag is set to `false` it works fine for oceania or australia as well.

**Comment by nnguyen52** [comment]
yes @neo7337, strict = false make this endpoint works. Thank you kindly! < 3

**Comment by ebwinters** [comment]
real issue is here: https://github.com/disease-sh/API/pull/1004#issuecomment-842295774

**Comment by puf17640** [comment]
this has been fixed by the latest PR and some commits I pushed afterwards to extend the fix.

https://disease.sh/v3/covid-19/continents/australia-oceania,
https://disease.sh/v3/covid-19/continents/australia and
https://disease.sh/v3/covid-19/continents/oceania
should all work now and return the same data.
