### ISSUE TITLE
[BUG] Why the historical/all does not return the recovered numbers anymore?

### ISSUE THREAD

**Issue by DhiaDjobbi** [disease-sh/API#1020]
I don't know why the number is recovered people is not updated since the **8/5/21** .
You find it here https://corona.lmao.ninja/v2/historical/all
The API returns the number of deaths and cases but doesn't return anymore the number of recovered people and shows 0.
 
![image](https://user-images.githubusercontent.com/40583006/130390948-7f76b5c0-271b-401a-887b-792d74d89baf.png)

**Comment by ebwinters** [comment]
Hi there. Johns Hopkins (the source for the timeline data) has stopped entering recovery data as of 8/5/21. The data is public, you can seen [here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv) if you check any country's data since 8/5 it is all zeroed out 😞 

Also, please use https://corona.lmao.ninja/v3/covid-19/historical/all instead of v2
