### ISSUE TITLE
[BUG] Invalid SSL certificate

### ISSUE THREAD

**Issue by andemerie** [disease-sh/API#1074]
**Describe the bug**
Cloudflare reports Invalid SSL certificate.

**To Reproduce**
- Go to https://disease.sh/
- Cloudflare error page 526 Invalid SSL certificate appears

**Expected behavior**
The site is working.

**Screenshots**
<img width="1084" alt="Screenshot 2023-09-16 at 18 27 09" src="https://github.com/disease-sh/API/assets/17383329/f3b31c3a-4670-4662-ab33-6889d1dcb165">

**Comment by rajathirumal** [comment]
still the same error. 🥲

**Comment by avimehenwal** [comment]
Experiencing the same as of 17-sep-2023.
Can someone please re-new the certificates or fix it please

**Comment by JosVermoesen** [comment]
Not much updates for Belgium since march 2023. I hope they fix it soon or later as autumn and winter will bring new data sadly. This API is/was a great project started in 2020. Meanwhile coming weeks I try to get my Angular app working with data from WHO delivering only data of 'cases' and 'deaths'.
https://github.com/JosVermoesen/ngb-covidstats

**Comment by pujux** [comment]
This should be fixed now. 👍
