### ISSUE TITLE
[Feature Req] South Africa - Scrape data from Wikipedia

### ISSUE THREAD

**Issue by skyzadev** [disease-sh/API#751]
**Is your feature request related to a problem? Please describe.**
Many government websites are too hard to scrape for detailed COVID-19 country data for various reasons (constantly changing formats, data posted as images etc). The official COVID-19 data sources from South Africa is an example of this.

Also, since the current NovelCOVID API endpoints do not provide granular country-level data, I had to go look for another reliable source for detailed South African COVID-19 data.

**Describe the solution you'd like**
https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/South_Africa_medical_cases (click "show") lists some COVID-19 data per province within South Africa. Replacing "South_Africa" within the URL with other country names brings up their equivalents. **Note**: I only checked a few countries and found most of them to return something, but in different formats.

I am only really interested in more granular South African data, which that Wikipedia source provides to some degree in what looks to be a scraper friendly format! Wikipedia could be used to scrape data for other countries as well, however, that would require a custom scraper to be coded for each country plus the maintenance work that goes along with it.

All-in-all what I am saying is that I am planning to write code to scrape the South African Wikipedia data myself, but why not write the scraper for this API rather then? It could serve as a data source for the **/gov/SouthAfrica** endpoint?

Let me know your thoughts, if approved I'll go ahead with writing it for this API.

**Comment by ebwinters** [comment]
This would be great to have for many more `/gov` endpoints, my only concern is that the data reported in the charts will not actually be _government reported_ data, as we have made sure the endpoints to be.

Looking at the sources listed for the South Africa, they are almost all from NICD and the Department of Health. 

I think you should write a South Africa scraper using the page linked above, since all the sources seem to be valid government ones, and if you plan to write more Wikipedia based endpoints, then you would need to check sources listed first

**Comment by puf17640** [comment]
I agree with Ethan

**Comment by skyzadev** [comment]
Closing... Will implement an PR for a new /gov/SouthAfrica endpoint

**Comment by puf17640** [comment]
@skyzadev no need to close the issue, just put `closes #751` into the PR description
