### ISSUE TITLE
[QUESTION] Meaning of field "updated" in covidAll data model

### ISSUE THREAD

**Issue by jmariani** [disease-sh/API#880]
covidAll data model contains a field called "updated".
At first I thought it was the last update date in Unix Time format, but converting to date results in a nonsensical date ("52703-02-07T07:25:59-05:00").
What kind of information the field contains, and in what format

Thank you in advance!

**Comment by ebwinters** [comment]
Confused what you mean by covidAll. If you're talking about covid19/all then it is currently 1601001820789, which is right

**Comment by jmariani** [comment]
Hi!
I'm talking about "/v3/covid-19/all", model "covidAll". I know the number is right, but how do I convert that number to a Date? What "1601001820789" does mean?

Thanks!

**Comment by EliteDaMyth** [comment]
@jmariani you were correct, it is an Unix timestamp. You can google how to resolve it to a proper date format. The thing you resolved is a proper date, just not in a readable format

**Comment by EliteDaMyth** [comment]
I am closing this issue, this is unrelated to the API.

**Comment by puf17640** [comment]
this is related to the API.

@jmariani the 'updated' field is a UNIX timestamp. In JS you would convert it to a date by doing `new Date(data.updated)`, but you should be able to find out how to perform that conversion in any language quite easily, since most languages support this particular conversion from unix timestamp to date.

**Comment by jmariani** [comment]
Thank you very much!
