### ISSUE TITLE
Provide an updated Postman collection in API/README.md

### ISSUE THREAD

**Issue by Collin-St** [disease-sh/API#886]
It's really old. The website's docs are great, but lots of people use Postman and this would be handy.

**Comment by ebwinters** [comment]
WDYM by this? Don't they have to update their stuff to reflect v3?

**Comment by Collin-St** [comment]
Who's they? Postman collections are free to make and share, so one of us could do it ourselves.

**Comment by Collin-St** [comment]
Oh, I see what you mean. Yeah we can't update the collection linked from the Postman article, but we can update the one we link to in the README.

**Comment by ebwinters** [comment]
Issue Update
--------------
The goal of this issue is now to create our own Postman collection reflecting our docs [here](disease.sh/docs)

[here](https://learning.postman.com/docs/getting-started/creating-the-first-collection/) is a good overview of how to create a collection

And in the end you will be able to update the postman collection link in our README to reflect the updated collection. [Here](https://documenter.getpostman.com/view/11144369/Szf6Z9B3?version=latest) is the current one (out of date) for reference:

**Comment by Dnguye92** [comment]
@ebwinters mind if I grab this one?

**Comment by ebwinters** [comment]
@Dnguye92 for sure!

**Comment by Dnguye92** [comment]
@ebwinters I have the collection file ready assuming you guys would be the ones to publish it

**Comment by ebwinters** [comment]
tbh i dont know how that works do we need a postman acct?

**Comment by Dnguye92** [comment]
@ebwinters yeah I believe so. I could just send you guys the collection file and you guys publish it or click "View in web" when you load the collection in postman and see how it looks then publish from there.

![image](https://user-images.githubusercontent.com/17717354/96056589-dc7d7180-0e3b-11eb-9f52-71d1511b0a0b.png)

**Comment by ebwinters** [comment]
Can you make a PR with the file included

**Comment by Dnguye92** [comment]
@ebwinters sure thing PR is here https://github.com/disease-sh/API/pull/917

**Comment by puf17640** [comment]
👍
