### ISSUE TITLE
[BUG] Recovered values for Canada

### ISSUE THREAD

**Issue by SuperMnr** [disease-sh/API#938]
**Describe the bug**

In historical statistics, all the recovered values for Canada are at 0.

**To Reproduce**

- Live URL for endpoint : https://disease.sh/v3/covid-19/historical/Canada?lastdays=30

**Comment by ebwinters** [comment]
This was by design, due to how JHUCSSSE format's their data for Canada only. You can see here, we are getting cases data from [this](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv) file: 
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/4297028/99079192-96781280-258d-11eb-8e55-496c4fdaa874.png">
Notice all of Canada's provinces are present, but there is no row with general Canada statistics.

Now [here](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv) is the source of recovered data: Notice there are no Rows for the provinces, but one for all of Canada:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/4297028/99079560-1ef6b300-258e-11eb-91eb-8c430fa4e0cd.png">

We did not program an edge case for this, since it just wasn't worth the time. JHU has province data in the recovered file for all other countries with provinces (like China), so Canda is the only real issue. If you want to fix it, see the `historical.js` file in the `scrapers` folder, and if you need help figuring out where to start, we can make a thread under this issue. Otherwise, if you don't want to fix it, I don't think it's high priority enough for else to either

**Comment by ebwinters** [comment]
@SuperMnr do you want to work on this or nah?

**Comment by nibble0101** [comment]
@ebwinters . It appears nobody else is interested in fixing this issue. Can I work on it?

**Comment by puf17640** [comment]
> @ebwinters  and @puf17640. It appears nobody else is interested in fixing this issue. Can I work on it?

Sure! I'll assign you, are you a member of our discord server? If not, you might wanna join so you can ask stuff if something isn't clear. :+1:

**Comment by nibble0101** [comment]
> and if you need help figuring out where to start, we can make a thread under this issue

@ebwinters  @puf17640  Can you guide me on how to proceed here?

**Comment by ebwinters** [comment]
First you need to set up your local env (steps in the readme). Then you'll need to mess around with the `historical.js` file to make an edge case for canada when we are matching recovered data with cases data. We match them up in a loop like this:
```
for each country/province in cases data
    finalData[country/province].cases = casesData.cases
    finalData[country/province].recovered = recoveredData.recovered
    finalData[country/province].deaths = deathsData.deaths
```
Right now there is no country/province in the recovered data, there is just canada with no province.

**Comment by nibble0101** [comment]
@ebwinters  Thanks.
