### ISSUE TITLE
[Feature Req] Worldometers specific/all dates

### ISSUE THREAD

**Issue by martoiu** [disease-sh/API#960]
It would be very handy if the Worldometers API could return all available dates. Or alternatively to be able to query a specific date in the past.

I store the values in a database and would like to see how the epidemic evolves, but I miss the historic data and sometimes I forget to update for more than two days.

Many thanks in advance,

Mihai

**Comment by ebwinters** [comment]
A couple things.
1. Worldometers TOS prohibits the storing of their data, which I guess we technically do, but it's more caching since we just reflect what's on their site, and update that value ever ~10min. We can't officially do this in our API, but it's open source, so if you want to deploy to your own server (probably free tier on Azure/AWS) feel free.
2. We have historical endpoints that you can use to query historical data. Check out our [docs](https://disease.sh/docs/)
