### ISSUE TITLE
Cyprus

### ISSUE THREAD

**Issue by Gregory95** [disease-sh/API#976]
Hello my name is Grigoris, i am junior software developer.  I would like to mention an issue that as a citizen of Cyprus bothers me.  First of all, you return Cyprus  as a country that belongs to Asia but its not.  Cyprus is an independent country and it belongs to European union since 2004.  North Cyprus is not recognized from UN as a legitimate state.  So please make sure that Cyprus belongs to Europe and the legitimate country is Republic of Cyprus (South Cyprus).

Sincerely,

Grigoris Kokozidis.

**Comment by ebwinters** [comment]
Hello.

We listing Cyprus as a part of Asia because our source does so: 
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/4297028/104846643-8b04d880-58a9-11eb-95fe-860389966499.png">

If it is really bothering you, you can make a PR with some edge case code to re-write the continent as Europe
