### ISSUE TITLE
Feature Request - Change how Vaccine data is returned

### ISSUE THREAD

**Issue by lukehecht** [disease-sh/API#978]
The daily vaccine data is returned with the date as the key (see below)
![image](https://user-images.githubusercontent.com/17548106/104954745-ba5a3900-59c0-11eb-83df-2c454c0b24b4.jpeg)
 but using numbers and special characters as JSON keys makes it a nightmare to work with. 

May I suggest reformatting the response to give each set of data its own object within the main data object? I’ve included a screenshot of the UK governments API to demonstrate 
![image](https://user-images.githubusercontent.com/17548106/104954769-c9d98200-59c0-11eb-9743-2e80e85067c4.jpeg)

**Comment by chcald** [comment]
Hello, I've fixed the problem, please let me access to commit

**Comment by ebwinters** [comment]
@chcald make a pull request

**Comment by chcald** [comment]
I do not have permission to push, I would need to push my branch to create the PR. Thanks

**Comment by ebwinters** [comment]
@chcald make a fork and push your changes there, then make a PR 😃

**Comment by ebwinters** [comment]
@chcald bro?

**Comment by comster** [comment]
Hmm, idk if this is the right thread but...

It would also be nice to include more data/fields which appears to be in the source like:

`total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million`

Total is nice, but since some require 2 doses to be "fully" vaccinated, it would be nice to have numbers that could be compared to the size of the population.

**Comment by comster** [comment]
@nik-suri I see that #993 somewhat addresses this, but unfortunately I see that it's still missing useful data provided, namely `people_fully_vaccinated`.  Any chance of getting that included in the `fullData` response?

**Comment by nik-suri** [comment]
@comster I see, this would require updates to the scraper `getVaccine.js` to include those data points in Redis as well. Since this issue is closed with the 2 PRs above, you may want to open the scraper enhancement as a new issue.

**Comment by puf17640** [comment]
can we close this?

**Comment by nik-suri** [comment]
@puf17640 Yes, this should be closed since the specific issue - reformatting the vaccine data response - has been merged in.

@comster Can you please open a new issue requesting the additional vaccine data fields?
